pipeline {
    agent any

    environment {
        APP_NAME = "book_service"
        IMAGE_TAG = "latest"
        LOCAL_IMAGE_DIR = "~/container_image"
        CUSTOM_WORKSPACE = "~/REST_Service/"
    }

    stages {

        stage('Prepare Workspace') {
            steps {
                sh "mkdir -p ${CUSTOM_WORKSPACE}"
            }
        }

        stage('Checkout') {
            steps {
                dir("${CUSTOM_WORKSPACE}") {
                    git url: 'https://github.com/haaskari/book_service_project.git', branch: 'main'
                }
            }
        }

        stage('Build with Maven') {
            steps {
                dir("${CUSTOM_WORKSPACE}/book_service_project/book-service") {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Container Image') {
            steps {
                dir("${CUSTOM_WORKSPACE}") {
                    sh """
                        docker build -t ${APP_NAME}:${IMAGE_TAG} .
                    """
                }
            }
        }

        stage('Save Image Locally') {
            steps {
                sh """
                    mkdir -p ${LOCAL_IMAGE_DIR}
                    docker save ${APP_NAME}:${IMAGE_TAG} -o ${LOCAL_IMAGE_DIR}/${APP_NAME}_${IMAGE_TAG}.tar
                """
            }
        }
    }
}
